### PR TITLE
Support the function to specify extra memory size to allocate in advance

### PR DESCRIPTION
**Pull request by moznion**
ref: #53

### CODE REVIEW

**Comment by goccy** [comment]
Thanks for reporting. But this behavior is not a specification.
Therefore, It do not need to switch by options.

Simply, what about the following code ?
## Compiler_lexer.cpp L15-16
```
+ static const int EXTEND_BUFFER_SIZE = 16; // this parameter is needed to correspond #53
- script_size = strlen(script) + 1;
+ script_size = strlen(script) + 1 + EXTEND_BUFFER_SIZE;
```

**Comment by moznion** [comment]
Well, how do we deal with this problem if memory size is shorter than hard-coded `EXTEND_BUFFER_SIZE`?

**Comment by goccy** [comment]
I modified the above code and created PR #56.
Please review this code > @moznion 

> Well, how do we deal with this problem if memory size is shorter than hard-coded EXTEND_BUFFER_SIZE?

Is it problem ?

**Comment by moznion** [comment]
Yes, if target code occupies memory which overs the maximum size then we cannot handle it.

Example for the above case;

```perl
s///;s///;s///;s///;s///;s///;s///;s///;s///;s///;
```

If this code is evaluated, it will occur SEGV.
It is silly case, but we cannot handle it indeed.

So I wish to configure the extend memory size.

**Comment by goccy** [comment]
If will support the above code, it must check buffer size enough or not for each tokens.
If there is a need, I will support.
This feature should not be supported as option.

**Comment by moznion** [comment]
Okay, I understood.
I've closed this pull request. Please apply #56.

**Pull request closed without merging**
